// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUjUf4-lY-9OaFxJnyDDu-SzrWhrDj7OY',
    appId: '1:1057882811150:web:e66adee9f9c729dc71855f',
    messagingSenderId: '1057882811150',
    projectId: 'doula-6b8a2',
    authDomain: 'doula-6b8a2.firebaseapp.com',
    storageBucket: 'doula-6b8a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqnzKGAHmeWEM5tYmT9a7ysE3E6Y_ouMk',
    appId: '1:5481212381:android:f6b1ac338db03b3f6c6e34',
    messagingSenderId: '5481212381',
    projectId: 'momsie-app',
    storageBucket: 'momsie-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD3lkrgf8i8AuNm4OqKzs3cnvKLO0DdfI',
    appId: '1:1057882811150:ios:ef2097eafdbfb28271855f',
    messagingSenderId: '1057882811150',
    projectId: 'doula-6b8a2',
    storageBucket: 'doula-6b8a2.appspot.com',
    iosClientId: '1057882811150-6h7ge6a7ire515h7lcah8vbuff0iueab.apps.googleusercontent.com',
    iosBundleId: 'com.momsie.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD3lkrgf8i8AuNm4OqKzs3cnvKLO0DdfI',
    appId: '1:1057882811150:ios:2f117a5e9453c60d71855f',
    messagingSenderId: '1057882811150',
    projectId: 'doula-6b8a2',
    storageBucket: 'doula-6b8a2.appspot.com',
    iosClientId: '1057882811150-48f832ds7j4treot5b2pmqbi9vqnj51f.apps.googleusercontent.com',
    iosBundleId: 'com.momsie.mobile.RunnerTests',
  );
}
